version: '3.4'

services:
  example:
    image: ${DOCKER_REGISTRY-}example
    links:
        - influx
        - cassandra
        - iotdb
    build:
      context: .
      dockerfile: src/example/Dockerfile
    ports:
        - "8080:8080"
    networks:
          - iotsharp-network

  influx:
        image: "quay.io/influxdb/influxdb:v2.0.4"
        restart: always
        container_name: influx
        ports:
         - "8086:8086"
        environment:
          TZ: "Asia/Shanghai"
        volumes:
         - ./data/influxdb-data:/var/lib/influxdb2
        command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt
        networks:
          - iotsharp-network

 
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - ./data/cassandra/commitlog:/var/lib/cassandra/commitlog
      - ./data/cassandra/hints:/var/lib/cassandra/hints
      - ./data/cassandra/data:/var/lib/cassandra/data
      - ./data/cassandra/saved_caches:/var/lib/cassandra/saved_caches
      - ./data/cassandra/logs:/var/log/cassandra      
    networks:
          - iotsharp-network

  iotdb:
   image: apache/iotdb:0.13.0-node
   restart: always
   container_name: iotdb
   ports:
         - 6667:6667
   networks:
          - iotsharp-network

networks: 
  iotsharp-network:
      driver:  bridge